server:
  port: 8772  
# spring配置
spring:
  application:
    profile: dev
    name: config-client-dev
# eureka配置，服务注册到哪里	
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/